/**
 * Golden Vectors Tests for TxIntent Cross-Language Verification
 *
 * These tests verify that the TypeScript implementation produces
 * the same CBOR encoding and EIP-712 digests as the Rust implementation.
 *
 * If these tests fail, there's a mismatch between Rust and TS implementations.
 */

import {
  TxIntent,
  AuthMode,
  encodeIntent,
  decodeIntent,
  buildEip712TypedData,
  computeLaneAPayload,
} from '../tx-intent.js';

// ============================================================================
// Golden Vectors from Rust (DO NOT MODIFY - must match Rust output)
// ============================================================================

// DevicePop Intent CBOR (hex) - generated by Rust
const DEVICE_POP_CBOR =
  '8b016a746573742d73636f7065782a3078313233343536373839303132333435363738393031323334353637383930313233343536373839306f504f5354202f74782f7375626d69745820e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8556d6964656d2d746573742d313233182a1b000001941f297c00197a6900736163636573732d746f6b656e2d69642d616263';

// WalletDirect Intent CBOR (hex) - generated by Rust
const WALLET_DIRECT_CBOR =
  '8b016a746573742d73636f7065782a3078616263646566303132333435363738396162636465663031323334353637383961626364656630316f504f5354202f74782f7375626d69745820e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8556f6964656d2d77616c6c65742d343536001b000001941f297c000101f6';

// Lane A Signature Payload (SHA256 hash, hex) - generated by Rust
const LANE_A_SIG_PAYLOAD =
  'aa6ac43dcd2426a61beb5c3af7781b36f02a429a536bb15f6a04617cbb5e7d3c';

// Lane B EIP-712 Digest (executor_id = 'arcana:local:dev', hex) - generated by Rust
const LANE_B_EIP712_DIGEST =
  '0x3634e531f1bc63614d87d67f98516b2ca62c7c65ed6c405f1327b9818dd05543';

// ============================================================================
// Golden Intent Fixtures
// ============================================================================

// SHA256("") = e3b0c4...
const EMPTY_BODY_HASH = new Uint8Array([
  0xe3, 0xb0, 0xc4, 0x42, 0x98, 0xfc, 0x1c, 0x14, 0x9a, 0xfb, 0xf4, 0xc8, 0x99,
  0x6f, 0xb9, 0x24, 0x27, 0xae, 0x41, 0xe4, 0x64, 0x9b, 0x93, 0x4c, 0xa4, 0x95,
  0x99, 0x1b, 0x78, 0x52, 0xb8, 0x55,
]);

function goldenDevicePopIntent(): TxIntent {
  return {
    version: 1,
    scopeId: 'test-scope',
    actorId: '0x1234567890123456789012345678901234567890',
    action: 'POST /tx/submit',
    argsHash: EMPTY_BODY_HASH,
    idempotencyKey: 'idem-test-123',
    nonce: BigInt(42),
    expiresAtMs: BigInt(1735689600000), // 2025-01-01 00:00:00 UTC
    chainId: BigInt(31337),
    authMode: AuthMode.DevicePop,
    accessTokenId: 'access-token-id-abc',
  };
}

function goldenWalletDirectIntent(): TxIntent {
  return {
    version: 1,
    scopeId: 'test-scope',
    actorId: '0xabcdef0123456789abcdef0123456789abcdef01',
    action: 'POST /tx/submit',
    argsHash: EMPTY_BODY_HASH,
    idempotencyKey: 'idem-wallet-456',
    nonce: BigInt(0),
    expiresAtMs: BigInt(1735689600000), // 2025-01-01 00:00:00 UTC
    chainId: BigInt(1), // Mainnet
    authMode: AuthMode.WalletDirect,
    accessTokenId: null,
  };
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substr(i, 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

// ============================================================================
// Tests
// ============================================================================

describe('Golden Vectors - Cross-Language Verification', () => {
  describe('CBOR Encoding', () => {
    test('DevicePop intent encodes to expected CBOR bytes', () => {
      const intent = goldenDevicePopIntent();
      const encoded = encodeIntent(intent);
      const encodedHex = bytesToHex(encoded);

      expect(encodedHex).toBe(DEVICE_POP_CBOR);
    });

    test('WalletDirect intent encodes to expected CBOR bytes', () => {
      const intent = goldenWalletDirectIntent();
      const encoded = encodeIntent(intent);
      const encodedHex = bytesToHex(encoded);

      expect(encodedHex).toBe(WALLET_DIRECT_CBOR);
    });

    test('DevicePop CBOR decodes correctly', () => {
      const bytes = hexToBytes(DEVICE_POP_CBOR);
      const decoded = decodeIntent(bytes);

      expect(decoded.version).toBe(1);
      expect(decoded.scopeId).toBe('test-scope');
      expect(decoded.actorId).toBe('0x1234567890123456789012345678901234567890');
      expect(decoded.action).toBe('POST /tx/submit');
      expect(decoded.idempotencyKey).toBe('idem-test-123');
      expect(decoded.nonce).toBe(BigInt(42));
      expect(decoded.chainId).toBe(BigInt(31337));
      expect(decoded.authMode).toBe(AuthMode.DevicePop);
      expect(decoded.accessTokenId).toBe('access-token-id-abc');
    });

    test('WalletDirect CBOR decodes correctly', () => {
      const bytes = hexToBytes(WALLET_DIRECT_CBOR);
      const decoded = decodeIntent(bytes);

      expect(decoded.version).toBe(1);
      expect(decoded.scopeId).toBe('test-scope');
      expect(decoded.actorId).toBe('0xabcdef0123456789abcdef0123456789abcdef01');
      expect(decoded.authMode).toBe(AuthMode.WalletDirect);
      expect(decoded.accessTokenId).toBeNull();
    });

    test('Roundtrip: encode -> decode -> encode produces same bytes', () => {
      const intent = goldenDevicePopIntent();
      const encoded1 = encodeIntent(intent);
      const decoded = decodeIntent(encoded1);
      const encoded2 = encodeIntent(decoded);

      expect(bytesToHex(encoded1)).toBe(bytesToHex(encoded2));
    });
  });

  describe('Lane A Signature Payload', () => {
    test('DevicePop intent produces expected Lane A payload', async () => {
      const intent = goldenDevicePopIntent();
      const payload = await computeLaneAPayload(intent);
      const payloadHex = bytesToHex(payload);

      expect(payloadHex).toBe(LANE_A_SIG_PAYLOAD);
    });

    test('Lane A payload is deterministic', async () => {
      const intent = goldenDevicePopIntent();
      const payload1 = await computeLaneAPayload(intent);
      const payload2 = await computeLaneAPayload(intent);

      expect(bytesToHex(payload1)).toBe(bytesToHex(payload2));
    });
  });

  describe('Lane B EIP-712', () => {
    test('WalletDirect intent produces expected typed data structure', () => {
      const intent = goldenWalletDirectIntent();
      const typedData = buildEip712TypedData(intent, 'arcana:local:dev');

      expect(typedData.domain.name).toBe('Arcana TxIntent');
      expect(typedData.domain.version).toBe('1');
      expect(typedData.domain.chainId).toBe(BigInt(1));
      expect(typedData.primaryType).toBe('TxIntent');
      expect(typedData.message.version).toBe(1);
      expect(typedData.message.authMode).toBe(1);
    });

    test('Different executor_id produces different salt', () => {
      const intent = goldenWalletDirectIntent();
      const typedData1 = buildEip712TypedData(intent, 'arcana:local:dev');
      const typedData2 = buildEip712TypedData(intent, 'arcana:prod:001');

      expect(typedData1.domain.salt).not.toBe(typedData2.domain.salt);
    });

    test('Different scope_id produces different salt', () => {
      const intent1 = goldenWalletDirectIntent();
      const intent2 = { ...goldenWalletDirectIntent(), scopeId: 'other-scope' };

      const typedData1 = buildEip712TypedData(intent1, 'arcana:local:dev');
      const typedData2 = buildEip712TypedData(intent2, 'arcana:local:dev');

      expect(typedData1.domain.salt).not.toBe(typedData2.domain.salt);
    });
  });

  describe('Cross-Language Rust Compatibility', () => {
    test('Rust CBOR can be decoded by TS', () => {
      const rustCbor = hexToBytes(DEVICE_POP_CBOR);
      const decoded = decodeIntent(rustCbor);

      // If we get here without throwing, Rust CBOR is compatible
      expect(decoded.version).toBe(1);
    });

    test('TS-encoded CBOR matches Rust-encoded CBOR', () => {
      const intent = goldenDevicePopIntent();
      const tsEncoded = encodeIntent(intent);
      const rustExpected = hexToBytes(DEVICE_POP_CBOR);

      expect(bytesToHex(tsEncoded)).toBe(bytesToHex(rustExpected));
    });
  });
});

